// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AI_Studio
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string AI_StudioString = "2dd7016f-e0cf-41b5-bc1a-ca24bd6b9662";
        public static Guid AI_Studio = new Guid(AI_StudioString);

        public const string guidAIStudioPackageCmdSetString = "c5d38240-1386-4b1c-8749-dcc909d58e0b";
        public static Guid guidAIStudioPackageCmdSet = new Guid(guidAIStudioPackageCmdSetString);

        public const string guidImagesString = "03bbd249-146e-4149-83d1-5114ba7f8392";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int AI_MenuGroup = 0x1000;
        public const int AI_CommandGroup = 0x1001;
        public const int AI_Menu = 0x1002;
        public const int AddUnitTests = 0x0000;
        public const int AddSummary = 0x0001;
        public const int AddComments = 0x0002;
        public const int Refactor = 0x0003;
        public const int Explain = 0x0004;
        public const int CodeIt = 0x0005;
        public const int SecurityCheck = 0x0006;
        public const int cmdidChatWindowCommand = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}